#
# Component Makefile
#

ifeq ($(CONFIG_RTOS_LIB_FREERTOS),y)
COMPONENT_ADD_INCLUDEDIRS += port
COMPONENT_ADD_INCLUDEDIRS += RTOS/FreeRTOS/include
COMPONENT_ADD_INCLUDEDIRS += RTOS/FreeRTOS/portable/GCC/$(CONFIG_MCU)

COMPONENT_SRCDIRS += port
COMPONENT_SRCDIRS += RTOS/FreeRTOS
COMPONENT_SRCDIRS += RTOS/FreeRTOS/portable/GCC/$(CONFIG_MCU)
endif

ifeq ($(CONFIG_RTOS),y)
COMPONENT_ADD_INCLUDEDIRS += oslib
COMPONENT_SRCDIRS += oslib

# remove all " in paths
COMPONENT_ADD_INCLUDEDIRS := $(shell echo $(COMPONENT_ADD_INCLUDEDIRS))
COMPONENT_SRCDIRS := $(shell echo $(COMPONENT_SRCDIRS))
endif